#!/bin/sh
DOCKER_IMAGE="workshop-criptografia-node"
docker inspect --type=image "${DOCKER_IMAGE}" > /dev/null 2>&1
if [ $? -ne 0 ]; then
  docker build -t ${DOCKER_IMAGE} .
fi
docker run -it --rm -v ${PWD}:/app ${DOCKER_IMAGE} sh
